---
sudo: false
dist: trusty
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true

deps:
  - codecov

install:
  - pip install tox codecov

script:
  - tox -e $TOXENV

after_success:
  - tox -e coverage-report
  - codecov
