# This file is automatically generated by the rmf-codegen project.
#
# The Python code generator is maintained by Lab Digital. If you want to
# contribute to this project then please do not edit this file directly
# but send a pull request to the Lab Digital fork of rmf-codegen at
# https://github.com/labd/rmf-codegen
from commercetools.client import BaseClient

from .api.api_request_builder import ApiRequestBuilder
from .frontastic.frontastic_request_builder import FrontasticRequestBuilder


class Client(BaseClient):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("url", "https://{project}-{customer}.frontastic.io")
        super().__init__(self, **kwargs)

    def frontastic(self) -> FrontasticRequestBuilder:
        return FrontasticRequestBuilder(
            client=self,
        )

    def api(self) -> ApiRequestBuilder:
        return ApiRequestBuilder(
            client=self,
        )
